version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: ~/code
    steps:
      - checkout
      - restore_cache:
          key: go-pkg-{{ checksum "go.sum" }}
      - run: ./build-release.sh
      - save_cache:
          paths:
            - /go/pkg
          key: go-pkg-{{ checksum "go.sum" }}
      - store_artifacts:
          path: bin
          destination: bin
