version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.17
    working_directory: ~/code
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y upx
      - run: ./build-release.sh
      - store_artifacts:
          path: bin
          destination: bin
